CREATE TABLE muscles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    name        VARCHAR(255)                            NOT NULL,
    slug        VARCHAR(255),
    body_region VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_muscles PRIMARY KEY (id)
);

ALTER TABLE muscles
    ADD CONSTRAINT uc_muscles_name UNIQUE (name);

ALTER TABLE muscles
    ADD CONSTRAINT uc_muscles_slug UNIQUE (slug);